[package]
name = "mac"
version = "0.1.0"
edition = "2021"

[dependencies]
# syn = { version = "2.0.77", features = ["full"] }
# proc-macro2 = "1.0"
# quote = { version = "1.0.*" }
cmd-proc-macro = "0.1.4"

[[bin]]
name = "mac"
path = "src/main.rs"

# [lib]
# proc-macro = true

